// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using ShoppingListDiploma.Data;

#nullable disable

namespace ShoppingListDiploma.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260514140000_AddPriorityPriceAndAssigneeToShoppingItems")]
partial class AddPriorityPriceAndAssigneeToShoppingItems
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        ApplicationDbContextModelSnapshot.BuildShoppingListModel(modelBuilder);
    }
}
