// <auto-generated />
using System;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListDiploma.Data;
using ShoppingListDiploma.Models;

#nullable disable

namespace ShoppingListDiploma.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
        BuildShoppingListModel(modelBuilder);
    }

    public static void BuildShoppingListModel(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
        {
            b.Property<string>("Id").HasColumnType("nvarchar(450)");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
            b.Property<string>("Name").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("NormalizedName").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedName").IsUnique().HasDatabaseName("RoleNameIndex").HasFilter("[NormalizedName] IS NOT NULL");
            b.ToTable("AspNetRoles", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
            b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
            b.Property<string>("RoleId").IsRequired().HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("RoleId");
            b.ToTable("AspNetRoleClaims", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("ClaimType").HasColumnType("nvarchar(max)");
            b.Property<string>("ClaimValue").HasColumnType("nvarchar(max)");
            b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserClaims", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
            b.Property<string>("ProviderKey").HasColumnType("nvarchar(450)");
            b.Property<string>("ProviderDisplayName").HasColumnType("nvarchar(max)");
            b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
            b.HasKey("LoginProvider", "ProviderKey");
            b.HasIndex("UserId");
            b.ToTable("AspNetUserLogins", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("nvarchar(450)");
            b.Property<string>("RoleId").HasColumnType("nvarchar(450)");
            b.HasKey("UserId", "RoleId");
            b.HasIndex("RoleId");
            b.ToTable("AspNetUserRoles", (string)null);
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.Property<string>("UserId").HasColumnType("nvarchar(450)");
            b.Property<string>("LoginProvider").HasColumnType("nvarchar(450)");
            b.Property<string>("Name").HasColumnType("nvarchar(450)");
            b.Property<string>("Value").HasColumnType("nvarchar(max)");
            b.HasKey("UserId", "LoginProvider", "Name");
            b.ToTable("AspNetUserTokens", (string)null);
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ApplicationUser", b =>
        {
            b.Property<string>("Id").HasColumnType("nvarchar(450)");
            b.Property<int>("AccessFailedCount").HasColumnType("int");
            b.Property<string>("ConcurrencyStamp").IsConcurrencyToken().HasColumnType("nvarchar(max)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<string>("DisplayName").HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Email").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<bool>("EmailConfirmed").HasColumnType("bit");
            b.Property<bool>("LockoutEnabled").HasColumnType("bit");
            b.Property<DateTimeOffset?>("LockoutEnd").HasColumnType("datetimeoffset");
            b.Property<string>("NormalizedEmail").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("NormalizedUserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.Property<string>("PasswordHash").HasColumnType("nvarchar(max)");
            b.Property<string>("PhoneNumber").HasColumnType("nvarchar(max)");
            b.Property<bool>("PhoneNumberConfirmed").HasColumnType("bit");
            b.Property<string>("SecurityStamp").HasColumnType("nvarchar(max)");
            b.Property<bool>("TwoFactorEnabled").HasColumnType("bit");
            b.Property<string>("UserName").HasMaxLength(256).HasColumnType("nvarchar(256)");
            b.HasKey("Id");
            b.HasIndex("NormalizedEmail").HasDatabaseName("EmailIndex");
            b.HasIndex("NormalizedUserName").IsUnique().HasDatabaseName("UserNameIndex").HasFilter("[NormalizedUserName] IS NOT NULL");
            b.ToTable("AspNetUsers", (string)null);
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.GroupInvitation", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<string>("InvitedByUserId").IsRequired().HasColumnType("nvarchar(450)");
            b.Property<string>("InvitedUserId").IsRequired().HasColumnType("nvarchar(450)");
            b.Property<DateTime?>("RespondedAtUtc").HasColumnType("datetime2");
            b.Property<int>("ShoppingGroupId").HasColumnType("int");
            b.Property<string>("Status").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("InvitedByUserId");
            b.HasIndex("InvitedUserId");
            b.HasIndex("ShoppingGroupId", "InvitedUserId", "Status");
            b.ToTable("GroupInvitations");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.GroupMember", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("ApplicationUserId").IsRequired().HasColumnType("nvarchar(450)");
            b.Property<DateTime>("JoinedAtUtc").HasColumnType("datetime2");
            b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<int>("ShoppingGroupId").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("ApplicationUserId");
            b.HasIndex("ShoppingGroupId", "ApplicationUserId").IsUnique();
            b.ToTable("GroupMembers");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ItemHistory", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("Action").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("ApplicationUserId").HasColumnType("nvarchar(450)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<string>("NewValue").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<string>("OldValue").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<int>("ShoppingItemId").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("ApplicationUserId");
            b.HasIndex("ShoppingItemId");
            b.ToTable("ItemHistories");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.Notification", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<bool>("IsRead").HasColumnType("bit");
            b.Property<string>("Message").IsRequired().HasMaxLength(1000).HasColumnType("nvarchar(1000)");
            b.Property<int?>("RelatedGroupId").HasColumnType("int");
            b.Property<int?>("RelatedInvitationId").HasColumnType("int");
            b.Property<int?>("RelatedItemId").HasColumnType("int");
            b.Property<int?>("RelatedListId").HasColumnType("int");
            b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<string>("Type").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("RelatedGroupId");
            b.HasIndex("RelatedInvitationId");
            b.HasIndex("RelatedItemId");
            b.HasIndex("RelatedListId");
            b.HasIndex("UserId");
            b.ToTable("Notifications");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingGroup", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<string>("Description").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<string>("OwnerId").HasColumnType("nvarchar(450)");
            b.HasKey("Id");
            b.HasIndex("OwnerId");
            b.ToTable("ShoppingGroups");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingItem", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<string>("AssignedToUserId").HasColumnType("nvarchar(450)");
            b.Property<string>("Category").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
            b.Property<string>("Comment").HasMaxLength(500).HasColumnType("nvarchar(500)");
            b.Property<string>("CreatedByUserId").HasColumnType("nvarchar(450)");
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<decimal?>("EstimatedPrice").HasColumnType("decimal(18,2)");
            b.Property<bool>("IsPurchased").HasColumnType("bit");
            b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
            b.Property<DateTime?>("PurchasedAtUtc").HasColumnType("datetime2");
            b.Property<string>("PurchasedByUserId").HasColumnType("nvarchar(450)");
            b.Property<string>("Priority").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.Property<decimal>("Quantity").HasColumnType("decimal(18,2)");
            b.Property<int>("ShoppingListId").HasColumnType("int");
            b.Property<string>("Unit").HasMaxLength(50).HasColumnType("nvarchar(50)");
            b.HasKey("Id");
            b.HasIndex("AssignedToUserId");
            b.HasIndex("CreatedByUserId");
            b.HasIndex("PurchasedByUserId");
            b.HasIndex("ShoppingListId");
            b.ToTable("ShoppingItems");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingList", b =>
        {
            b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
            b.Property<DateTime>("CreatedAtUtc").HasColumnType("datetime2");
            b.Property<bool>("IsArchived").HasColumnType("bit");
            b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
            b.Property<int>("ShoppingGroupId").HasColumnType("int");
            b.HasKey("Id");
            b.HasIndex("ShoppingGroupId");
            b.ToTable("ShoppingLists");
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
        {
            b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null).WithMany().HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", null).WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.GroupMember", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "ApplicationUser").WithMany("GroupMemberships").HasForeignKey("ApplicationUserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.HasOne("ShoppingListDiploma.Models.ShoppingGroup", "ShoppingGroup").WithMany("Members").HasForeignKey("ShoppingGroupId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("ApplicationUser");
            b.Navigation("ShoppingGroup");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.GroupInvitation", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "InvitedByUser").WithMany("SentGroupInvitations").HasForeignKey("InvitedByUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "InvitedUser").WithMany("ReceivedGroupInvitations").HasForeignKey("InvitedUserId").OnDelete(DeleteBehavior.Restrict).IsRequired();
            b.HasOne("ShoppingListDiploma.Models.ShoppingGroup", "ShoppingGroup").WithMany().HasForeignKey("ShoppingGroupId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("InvitedByUser");
            b.Navigation("InvitedUser");
            b.Navigation("ShoppingGroup");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ItemHistory", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "ApplicationUser").WithMany("ItemHistories").HasForeignKey("ApplicationUserId").OnDelete(DeleteBehavior.SetNull);
            b.HasOne("ShoppingListDiploma.Models.ShoppingItem", "ShoppingItem").WithMany("HistoryEntries").HasForeignKey("ShoppingItemId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("ApplicationUser");
            b.Navigation("ShoppingItem");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.Notification", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.GroupInvitation", "RelatedInvitation").WithMany("Notifications").HasForeignKey("RelatedInvitationId").OnDelete(DeleteBehavior.NoAction);
            b.HasOne("ShoppingListDiploma.Models.ShoppingGroup", "RelatedGroup").WithMany().HasForeignKey("RelatedGroupId").OnDelete(DeleteBehavior.NoAction);
            b.HasOne("ShoppingListDiploma.Models.ShoppingItem", "RelatedItem").WithMany().HasForeignKey("RelatedItemId").OnDelete(DeleteBehavior.NoAction);
            b.HasOne("ShoppingListDiploma.Models.ShoppingList", "RelatedList").WithMany().HasForeignKey("RelatedListId").OnDelete(DeleteBehavior.NoAction);
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "User").WithMany("Notifications").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("RelatedGroup");
            b.Navigation("RelatedInvitation");
            b.Navigation("RelatedItem");
            b.Navigation("RelatedList");
            b.Navigation("User");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingGroup", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "Owner").WithMany().HasForeignKey("OwnerId").OnDelete(DeleteBehavior.SetNull);
            b.Navigation("Owner");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingItem", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "AssignedToUser").WithMany().HasForeignKey("AssignedToUserId").OnDelete(DeleteBehavior.SetNull);
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "CreatedByUser").WithMany().HasForeignKey("CreatedByUserId").OnDelete(DeleteBehavior.Restrict);
            b.HasOne("ShoppingListDiploma.Models.ApplicationUser", "PurchasedByUser").WithMany().HasForeignKey("PurchasedByUserId").OnDelete(DeleteBehavior.Restrict);
            b.HasOne("ShoppingListDiploma.Models.ShoppingList", "ShoppingList").WithMany("Items").HasForeignKey("ShoppingListId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("AssignedToUser");
            b.Navigation("CreatedByUser");
            b.Navigation("PurchasedByUser");
            b.Navigation("ShoppingList");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingList", b =>
        {
            b.HasOne("ShoppingListDiploma.Models.ShoppingGroup", "ShoppingGroup").WithMany("ShoppingLists").HasForeignKey("ShoppingGroupId").OnDelete(DeleteBehavior.Cascade).IsRequired();
            b.Navigation("ShoppingGroup");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ApplicationUser", b =>
        {
            b.Navigation("GroupMemberships");
            b.Navigation("ItemHistories");
            b.Navigation("Notifications");
            b.Navigation("ReceivedGroupInvitations");
            b.Navigation("SentGroupInvitations");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.GroupInvitation", b =>
        {
            b.Navigation("Notifications");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingGroup", b =>
        {
            b.Navigation("Members");
            b.Navigation("ShoppingLists");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingItem", b =>
        {
            b.Navigation("HistoryEntries");
        });

        modelBuilder.Entity("ShoppingListDiploma.Models.ShoppingList", b =>
        {
            b.Navigation("Items");
        });
    }
}
